
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/d66-social
    username: d66
    password: d66
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect